version: "3.8"
services:
    postgres:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypgdbpass
        volumes:
            - postgres_data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: mypgadminpass
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - postgres

volumes:
    postgres_data:
    pgadmin_data:
